config/routes.rb
Bookser::Application.routes.draw do

  root :to => "books#index"

  get "/login" => "authorization#login", :as => :login
  put "/login" => "authorization#authentificate", :as => :authentificate
  delete "/login" => "authorization#logout", :as => :logout
  
  resources :users do
    resources :books
  end

  resources :books

  resources :tags

end

app/models/book.rb
# Model represents a book.
# Book belongs to one user and cannot be created without specifying related user.
# Book can have tags.
#
# PdfUploader class from carierwave gem is used for storing book's data.
# It's configuration can be found at app_dir/config/initializers/carrierwave.rb and app_dir/app/uploaders/pdf_uploader.rb
# Tags can be assigned throught model's virtual attr :tags_string separated by space.
#
# Usage:
#
# Book.create :author => "Mr Nobody", :title => "About nothing", :user_id => @user.id, :tags_string => "sci-fi drama commedy"
# Will create a new book for a specifyed user with author name: Mr Nobody, title: About nothing  
# and 3 tags sci-fi, drama and commedy. Tags are fetched from the database or created as new if there is no tag with such name.
# Todo:
#
# Add author and title format validation
#

class Book < ActiveRecord::Base
  validates_presence_of :author, :title, :user_id

  attr_writer :tags_string
  attr_accessible :author, :title, :pdf, :tags_string

  has_many :taggings, :dependent => :destroy
  has_many :tags, :through => :taggings

  belongs_to :user

  mount_uploader :pdf, PdfUploader

  after_save :apply_tags

  def tags_string
    @tags_string || self.tags.map(&:name).join(" ")
  end

  private 

  def apply_tags
    self.tags = tags_string.split(" ").map do |tag_name|
      Tag.find_or_create_by_name tag_name
    end
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  # GET /books
  # GET /books.xml
  def index
    # @books = Book.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @books }
    end
  end

  # GET /books/1
  # GET /books/1.xml
  def show
    @book = Book.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @book }
    end
  end

  # GET /books/new
  # GET /books/new.xml
  def new
    @book = Book.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @book }
    end
  end

  # GET /books/1/edit
  def edit
    @book = Book.find(params[:id])
  end

  # POST /books
  # POST /books.xml
  def create
    @book = Book.new(params[:book])
    @book.user = @user

    respond_to do |format|
      if @book.save
        format.html { redirect_to([@user, @book], :notice => 'Book was successfully created.') }
        format.xml  { render :xml => @book, :status => :created, :location => @book }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @book.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /books/1
  # PUT /books/1.xml
  def update
    @book = Book.find(params[:id])

    respond_to do |format|
      if @book.update_attributes(params[:book])
        format.html { redirect_to([@user, @book], :notice => 'Book was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @book.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.xml
  def destroy
    @book = Book.find(params[:id])
    @book.destroy

    respond_to do |format|
      format.html { redirect_to(books_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<%= form_for([@user, @book], :html => {:multipart => true}) do |f| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% @book.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :author %><br />
    <%= f.text_field :author %>
  </div>
  <div class="field">
    <%= f.label :tags %><br />
    <%= f.text_field :tags_string %>
  </div>
  <% if @book.pdf_url %>
    <div class="field">
      <%= f.label :pdf_url %><br />
      <%= link_to @book.pdf_url, @book.pdf_url %>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :upload_new_pdf %><br />
    <%= f.file_field :pdf %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing book</h1>

<%= render 'form' %>

<%= link_to 'Show', [@user, @book] %> |
<%= link_to 'Back', user_books_path(@user) %>

app/views/books/index.html.erb
<h1>Listing books</h1>
<table>
  <tr>
    <th>Title</th>
    <th>Author</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @user.books.each do |book| %>
  <tr>
    <td><%= book.title %></td>
    <td><%= book.author %></td>
    <td><%= link_to 'Show', [@user, book] %></td>
    <td><%= link_to 'Edit', edit_user_book_path(@user,book) %></td>
    <td><%= link_to 'Destroy', [@user, book], :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Book', new_user_book_path(@user) %>

app/views/books/new.html.erb
<h1>New book</h1>

<%= render 'form' %>

<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @book.title %>
</p>

<p>
  <b>Author:</b>
  <%= @book.author %>
</p>


<%= link_to 'Edit', edit_user_book_path(@user, @book) %> |
<%= link_to 'Back', user_books_path(@user) %>